---
- name: Set up scenario
  debug:
    msg: "Setting up '{{ scenario }}'.  {{ scenario_comment }}"

- name: Implement traffic shaping per node
  include_tasks:
    file: ./shape.yaml
  loop: "{{ vms.keys()|list }}"
  vars:
    username: root
    ssh_params: "-o ForwardAgent=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i {{ user_ssh_pub_id_filename }}"
    vm_name: "{{ item }}"
