---
all:
  hosts:
    localhost:
  vars:
    vms:
      myrouter:
        ip: 192.168.2.1
        machine_id: 1
#      worker1:
#        ip: 192.168.2.2
#        machine_id: 2
#      worker2:
#        ip: 192.168.2.3
#        machine_id: 3
