---
all:
  hosts:
    localhost:
  vars:
    vms:
      worker0:
        ip: 192.168.122.10
        machine_id: 1
      worker1:
        ip: 192.168.122.11
        machine_id: 2
      worker2:
        ip: 192.168.122.12
        machine_id: 3
