---
- name: Install Fedora
  hosts: localhost
  gather_facts: true
  become: false
  vars:
    use_dhcp: False
    libvirt_connection: "qemu+tcp:///system"
    user_ssh_pub_id_filename: ~/.ssh/id_rsa.pub
    net_domain: ".example.com"
    net_if: "enp1s0"
    ip_netmask: "255.255.255.0"
    ip_gateway: "192.168.122.1"
    nameserver: "8.8.8.8"
    repo: "https://download.fedoraproject.org/pub/fedora/linux/releases/{{ fedora_version }}/Everything/x86_64/os"
  roles:
    - fedora-generic
  tags:
    - buildvms

- name: Implement traffic shapping
  hosts: all
  gather_facts: true
  become: false
  roles:
    - traffic-shapping
  tags:
    - trafficshape
